/**
 * Build lib/client.js (the browser bundle) from dict/ru/*.json.
 *
 * lib/client.js is committed so users installing the pack from GitHub or npm
 * never need a build step. Run this after editing dictionaries:
 *
 *   node scripts/build.mjs
 *
 * Reads every dict/ru/<namespace>.json and emits one self-contained bundle in
 * the harness client-module loader format (window.__ModuleLoader__.load) —
 * the same shape the official packages' client bundles use. Raw ESM breaks
 * the combo script parser and kills the whole app boot.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dictDir = join(root, 'dict', 'ru')
const outFile = join(root, 'lib', 'client.js')

let files
try {
  files = readdirSync(dictDir).filter((f) => f.endsWith('.json')).sort()
} catch {
  console.error('build: dict/ru/ not found — nothing to build')
  process.exit(1)
}
if (files.length === 0) {
  console.error('build: dict/ru/ is empty — nothing to build')
  process.exit(1)
}

const dictionaries = {}
for (const file of files) {
  const ns = file.replace(/\.json$/, '')
  dictionaries[ns] = JSON.parse(readFileSync(join(dictDir, file), 'utf8'))
}

const banner = `// GENERATED by scripts/build.mjs — do not edit by hand.
// Edit dict/ru/*.json and run \`node scripts/build.mjs\` instead.
// Format: harness client-module loader bundle (window.__ModuleLoader__.load).
`

const body = `window.__ModuleLoader__.load({
	id: "deepseek-harness-locale-ru",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

		const LANGUAGE = { id: 'ru', label: 'Русский', fallback: 'en' };

		const DICTIONARIES = ${JSON.stringify(dictionaries, null, 2)};

		const inject = ['locale'];

		function apply(ctx) {
			ctx.effect(
				() => ctx.locale.addLanguage(LANGUAGE),
				'deepseek-harness-locale-ru: language',
			)
			for (const [ns, dict] of Object.entries(DICTIONARIES)) {
				ctx.effect(
					() => ctx.locale.register(ns, 'ru', dict),
					\`deepseek-harness-locale-ru: \${ns} dictionary\`,
				)
			}
		}

		exports.name = 'deepseek-harness-locale-ru';
		exports.apply = apply;
		exports.inject = inject;
		return module.exports;
	},
});
`

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, banner + body)
const namespaces = Object.keys(dictionaries).length
const keys = Object.values(dictionaries).reduce((sum, d) => sum + Object.keys(d).length, 0)
console.log(`build: wrote ${outFile} (${namespaces} namespaces, ${keys} keys)`)
